# Generated by Django 5.0.6 on 2024-12-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=255)),
                ('subcategory', models.CharField(default='', max_length=255)),
                ('product_name', models.CharField(help_text='Enter Your Product Name', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(upload_to='products_images/')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
